Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Senith.Models
{
    public class Ticket
    {
        public string Destino { get; set; }
        public string HoraSalida { get; set; }
        public string Clase { get; set; }
        public Boolean Disponible { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Senith.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Senith.Seeds;
using Senith.Models;
using System.Data;
using System.Data.SqlClient;

namespace Senith.Controllers
{
    public class TicketController : Controller
    {
        // string connectionString = @"Data Source = (local)\sqle2017; Initial Catalog = SenithDB;  Integrated Security=True";

        private TicketsSeeder _ticketSeeder;

        public TicketController()
        {
            _ticketSeeder = new TicketsSeeder();
        }

        // GET: Ticket
        [HttpGet]
        public ActionResult MostrarTickets()
        {
            ViewBag.Message = "El listado de vuelo es: ";

            // DataTable dtblTicket = new DataTable();
            // using (SqlConnection sqlCon = new SqlConnection(connectionString))
            // {
                // sqlCon.Open();
                // SqlDataAdapter sqlDa = new SqlDataAdapter("SELECT * FROM Ticket", sqlCon);
              //  sqlDa.Fill(dtblTicket);
            //}

            var model = _ticketSeeder.ObtenerTickets();

            return View(model);
        }

        [HttpGet]
        public ActionResult ReservarTicket()
        {
            ViewBag.Message = "Por favor, proceda a reservar su Ticket de vuelo: ";

            return View(new Ticket());
        }

        [HttpPost]
        public ActionResult ReservarTicket(FormatException collection)
        {
            ViewBag.Message = "Por favor, proceda a reservar su Ticket de vuelo: ";

            return View(new Ticket());

        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SENITH - Ticket Review</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("SENITH - Ticket Review", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Reservar", "MostrarTickets", "Ticket")</li>
                    <li>@Html.ActionLink("Mostrar Tickets", "ReservarTickets", "Ticket")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Ticket/MostrarTickets.cshtml
@model List<Senith.Models.Ticket>

@{
    ViewBag.Title = "MostrarTickets";
}

<h2>MostrarTickets</h2>
<h3>@ViewBag.Message</h3>

<div>
    Mostrando @Model.Count tickets
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Destino</th>
            <th>Hora de Salida</th>
            <th>Clase de vuelo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var ticket in Model)
        {
            var disponible = string.Empty;

            if (!ticket.Disponible)
            {
                disponible = "Danger";
            }

            <tr class="disponible">
                <td>
                    @ticket.Destino
                </td>
                <td>
                    @ticket.HoraSalida
                </td>
                <td>
                    @ticket.Clase
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Ticket/ReservarTicket.cshtml
@model Senith.Models.Ticket

@{
    ViewBag.Title = "ReservarTicket";
}

<h2>ReservarTicket</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Destino, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destino, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destino, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoraSalida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraSalida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraSalida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Clase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Clase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Clase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Disponible, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Disponible)
                    @Html.ValidationMessageFor(model => model.Disponible, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>